
-- FONTS
resource.AddFile("resource/fonts/exocet-light.ttf")
resource.AddFile("resource/fonts/franklin-gothic-book.ttf")

-- SOUNDS
resource.AddFile("sound/vampire_slayer/gib_01.wav")
resource.AddFile("sound/vampire_slayer/gib_02.wav")
resource.AddFile("sound/vampire_slayer/gib_03.wav")
resource.AddFile("sound/vampire_slayer/weapons/winchester_01.wav")
resource.AddFile("sound/vampire_slayer/weapons/winchester_powered_02.wav")
resource.AddFile("sound/vampire_slayer/weapons/thunder5_01.wav")
resource.AddFile("sound/vampire_slayer/weapons/thunder5_02.wav")
resource.AddFile("sound/vampire_slayer/vo/latin_prayer_01.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_danger_01.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_laugh_01.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_laugh_02.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_laugh_03.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_laugh_04.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_taunt_01.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_taunt_02.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_taunt_03.wav")
resource.AddFile("sound/vampire_slayer/vo/vampire_taunt_04.wav")
resource.AddFile("sound/weapons/590/m3_bullet.mp3")
resource.AddFile("sound/weapons/590/m3_draw.mp3")
resource.AddFile("sound/weapons/590/m3_insertshell.mp3")
resource.AddFile("sound/weapons/590/m3_pump.mp3")
resource.AddFile("sound/weapons/590/m3-1.wav")
resource.AddFile("sound/weapons/627/bulletout_1.mp3")
resource.AddFile("sound/weapons/627/bulletout_2.mp3")
resource.AddFile("sound/weapons/627/bulletout_3.mp3")
resource.AddFile("sound/weapons/627/bullets_in.mp3")
resource.AddFile("sound/weapons/627/wheel_in.mp3")
resource.AddFile("sound/weapons/627/wheel_out.mp3")
resource.AddFile("sound/weapons/dbarrel/barreldown.mp3")
resource.AddFile("sound/weapons/dbarrel/barrelup.mp3")
resource.AddFile("sound/weapons/dbarrel/xm1014_insertshell.mp3")
resource.AddFile("sound/weapons/dbarrel/xm1014-1.wav")
resource.AddFile("sound/weapons/dmg_colt1911/de_clipin.mp3")
resource.AddFile("sound/weapons/dmg_colt1911/de_clipout.mp3")
resource.AddFile("sound/weapons/dmg_colt1911/de_slideback.mp3")
resource.AddFile("sound/weapons/dmg_colt1911/deagle-1.wav")
resource.AddFile("sound/weapons/dmg_colt1911/draw.mp3")
resource.AddFile("sound/weapons/winchester73/w73hammer.mp3")
resource.AddFile("sound/weapons/winchester73/w73insertshell.mp3")
resource.AddFile("sound/weapons/winchester73/w73pump.mp3")
resource.AddFile("sound/weapons/m60/m60_boxin.mp3")
resource.AddFile("sound/weapons/m60/m60_boxout.mp3")
resource.AddFile("sound/weapons/m60/m60_chain.mp3")
resource.AddFile("sound/weapons/m60/m60_coverdown.mp3")
resource.AddFile("sound/weapons/m60/m60_coverup.mp3")
resource.AddFile("sound/weapons/m60/m60-1.wav")

-- MODELS
resource.AddFile("models/brewstersmodels/thesimsbustinout/aristoscratch_pool_cue.mdl")
resource.AddFile("models/freeman/cross.mdl")
resource.AddFile("models/weapons/f_dmgf_co1911.mdl")
resource.AddFile("models/weapons/v_doublebarrl.mdl")
resource.AddFile("models/weapons/v_shot_mberg_590.mdl")
resource.AddFile("models/weapons/v_swmodel_627.mdl")
resource.AddFile("models/weapons/v_winchester1873.mdl")
resource.AddFile("models/weapons/v_m60machinegun.mdl")
resource.AddFile("models/weapons/s_dmgf_co1911.mdl")
resource.AddFile("models/weapons/w_double_barrel_shotgun.mdl")
resource.AddFile("models/weapons/w_mossberg_590.mdl")
resource.AddFile("models/weapons/w_sw_model_627.mdl")
resource.AddFile("models/weapons/w_winchester_1873.mdl")
resource.AddFile("models/weapons/w_m60_machine_gun.mdl")
resource.AddFile("models/weapons/arccw/stake_att/antivampire_stake.mdl")

-- MATERIALS
resource.AddFile("materials/models/brewstersmodels/simsbustinout/pooltable_overlord.vmt")
resource.AddSingleFile("materials/models/freeman/cross.vmt")
resource.AddSingleFile("materials/models/freeman/cross_diffuse.vtf")
resource.AddSingleFile("materials/models/freeman/cross_specular.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/colt 1911/frame norm.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/colt 1911/frame.vmt")
resource.AddSingleFile("materials/models/weapons/v_models/colt 1911/frame.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/colt 1911/slide norm.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/colt 1911/slide.vmt")
resource.AddSingleFile("materials/models/weapons/v_models/colt 1911/slide.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/dbarrel/dif.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/dbarrel/doubleba.vmt")
resource.AddSingleFile("materials/models/weapons/v_models/dbarrel/spec.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/dbarrel/spec2.vtf")
resource.AddFile("materials/models/weapons/v_models/enron_winchester/shell.vmt")
resource.AddFile("materials/models/weapons/v_models/enron_winchester/winchester.vmt")
resource.AddSingleFile("materials/models/weapons/v_models/enron_winchester/shell_ref.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/enron_winchester/winchester_normal.vtf")
resource.AddFile("materials/models/weapons/v_models/foregrip_stake/anti-vampire stake.vmt")
resource.AddSingleFile("materials/models/weapons/v_models/mossberg590/diffuse.vmt")
resource.AddSingleFile("materials/models/weapons/v_models/mossberg590/mossberg.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/mossberg590/mossberg_gloss.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/mossberg590/mossberg_normal.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/mossberg590/shotgun_shell.vmt")
resource.AddFile("materials/models/weapons/v_models/sw627/baked.vmt")
resource.AddSingleFile("materials/models/weapons/v_models/sw627/baked_normal.vtf")
resource.AddFile("materials/models/weapons/v_models/kimono_twinke_m60/ammobox.vmt")
resource.AddFile("materials/models/weapons/v_models/kimono_twinke_m60/body.vmt")
resource.AddFile("materials/models/weapons/v_models/kimono_twinke_m60/body2.vmt")
resource.AddFile("materials/models/weapons/v_models/kimono_twinke_m60/fore.vmt")
resource.AddSingleFile("materials/models/weapons/v_models/kimono_twinke_m60/ammobox_norm.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/kimono_twinke_m60/body_norm.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/kimono_twinke_m60/body2_norm.vtf")
resource.AddSingleFile("materials/models/weapons/v_models/kimono_twinke_m60/fore_norm.vtf")
resource.AddSingleFile("materials/models/weapons/w_models/colt 1911/frame.vmt")
resource.AddSingleFile("materials/models/weapons/w_models/colt 1911/slide.vmt")
resource.AddSingleFile("materials/models/weapons/w_models/dbarrel/doubleba.vmt")
resource.AddSingleFile("materials/models/weapons/w_models/enron_winchester/winchester.vmt")
resource.AddSingleFile("materials/models/weapons/w_models/w_sw627/baked.vmt")
resource.AddSingleFile("materials/models/weapons/w_models/kimono_twinke_m60/ammobox.vmt")
resource.AddSingleFile("materials/models/weapons/w_models/kimono_twinke_m60/body.vmt")
resource.AddSingleFile("materials/models/weapons/w_models/kimono_twinke_m60/body2.vmt")
resource.AddSingleFile("materials/models/weapons/w_models/kimono_twinke_m60/fore.vmt")
resource.AddSingleFile("materials/models/weapons/x_models/colt 1911/frame.vmt")
resource.AddSingleFile("materials/models/weapons/x_models/colt 1911/slide.vmt")
resource.AddSingleFile("materials/models/weapons/x_models/mossberg590/diffuse.vmt")
resource.AddSingleFile("materials/models/weapons/x_models/mossberg590/shotgun_shell.vmt")

-- WORKSHOP
--[[
resource.AddWorkshop("128091208") -- M9K Heavy Weapons
resource.AddWorkshop("128093075") -- M9K Small Arms
resource.AddWorkshop("128089118") -- M9K Assault Rifles
resource.AddWorkshop("130832570") -- Wooden Cross
resource.AddWorkshop("2169575427") -- Offhand Stake
resource.AddWorkshop("848825041") -- Billiards Pack
]]
